"use client";

import { Canvas } from "@react-three/fiber";
import "./globals.css";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import { Loader } from "@react-three/drei";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fleava",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Canvas gl={{ antialias: false, alpha: false }} dpr={1.5}>
          <Suspense fallback={null}>{children}</Suspense>
          <Loader />
        </Canvas>
      </body>
    </html>
  );
}
